export enum NotificationChannel {
  WHATSAPP = 'WHATSAPP',
  WEB = 'WEB',
  EMAIL = 'EMAIL'
}

export enum QuoteNotificationEvent {
  QUOTE_CREATED = 'QUOTE_CREATED',
  QUOTE_VIEWED = 'QUOTE_VIEWED',
  QUOTE_DOWNLOADED = 'QUOTE_DOWNLOADED',
  QUOTE_IN_PROGRESS = 'QUOTE_IN_PROGRESS',
  QUOTE_QUOTED = 'QUOTE_QUOTED',
  QUOTE_REJECTED = 'QUOTE_REJECTED',
  QUOTE_INVOICED = 'QUOTE_INVOICED'
}

export enum NotificationScope {
  GLOBAL = 'GLOBAL',
  OWN_BRANCH = 'OWN_BRANCH'
}

export enum WhatsappNotificationTemplate {
  QUOTE_WEB_NOTIFICATION = 'QUOTE_WEB_NOTIFICATION',
  QUOTE_WEB_NOTIFICATION_ICONS = 'QUOTE_WEB_NOTIFICATION_ICONS',
  QUOTE_WORKFLOW_MANAGER_NEW = 'QUOTE_WORKFLOW_MANAGER_NEW',
  QUOTE_WORKFLOW_MANAGER_VIEWED = 'QUOTE_WORKFLOW_MANAGER_VIEWED',
  QUOTE_WORKFLOW_MANAGER_AFTER_DOWNLOAD = 'QUOTE_WORKFLOW_MANAGER_AFTER_DOWNLOAD',
  QUOTE_WORKFLOW_MANAGER_REMINDER_PENDING_ERP = 'QUOTE_WORKFLOW_MANAGER_REMINDER_PENDING_ERP',
  QUOTE_WORKFLOW_MANAGER_REJECT_REASON_PENDING_ERP = 'QUOTE_WORKFLOW_MANAGER_REJECT_REASON_PENDING_ERP'
}
