


GET http://localhost:3000/api/threads

### 
POST http://localhost:3000/api/threads/messages?pageSize=100
Content-Type: application/json

{
  "threadId":""
}

### Get by id
GET http://localhost:3000/api/threads/thread_ET02VFKLnXdFnyZUz1owFAdt



### Get Quotes
GET http://localhost:3000/api/quotes
