### Generate Quote PDF
POST http://localhost:3000/api/quote-versions/64d3f563-3350-4db9-b1a3-6b2550b899ec/artifacts/pdf
Authorization: Bearer 

### GetDrafts
GET http://localhost:3000/api/quote-versions/4e42bcdd-1c31-47e0-ad9c-77eca1ed58f2/draft
Authorization: Bearer 


### Send quote PDF
POST http://localhost:3000/api/quote-versions/send-quote-pdf
Content-Type: application/json

{
 
  "quoteVersionId":""

}

### Get pdf presigne
GET http://localhost:3000/api/quote-versions/8e524e01-415a-4a1e-ad27-7400c0b1cd67/artifacts/pdf/latest



