### Get Quote display
GET http://localhost:3000/api/quotes/5019e0fb-fbde-4eff-a306-d3a668ea3c76/display
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJkNGQ0NWZjLTVmN2EtNGM5My1iNjI2LWJhYTNkYjEyMTgyNyIsImlhdCI6MTc2MjgxMzIyMywiZXhwIjoxNzYyODIwNDIzfQ.iZTQOObN6cy3noI9ro7KX8cGwfNT5y6edn8cwP5Y8Js

### Get Quote File
GET http://localhost:3000/api/quotes/ME7a1dd84f00d0e1bbb9a5a43ab64a2eb9.pdf/quote